### ISSUE TITLE
report - cyclonedxjson not a recognized plugin.

### ISSUE THREAD

**Issue by nexeh** [tern-tools/tern#1026]
**Describe the bug**
`report - cyclonedxjson not a recognized plugin.`

i know this is new. i see it in the codebase. nothing jumped out to me as what's wrong but due to this error there is no output. other formats are working fine. Im really interested in exploring this tool more! 

**To Reproduce**
1. `docker run --privileged --device /dev/fuse -v /var/run/docker.sock:/var/run/docker.sock ternd report -f cyclonedxjson -i openjdk:13-alpine > sbom.json`

**Error in terminal**
```
`report - cyclonedxjson not a recognized plugin.`
```

**Expected behavior**
cyclonedxjson 

**Environment you are running Tern on**
Enter all that apply
- Docker Container

**Comment by rnjudge** [comment]
Thanks for your interest in Tern @nexeh. The reason you're seeing this issue is because we have not yet cut a release with the latest cycleonedx format changes. When you run Tern in a Docker container, it uses this [Dockerfile](https://github.com/tern-tools/tern/blob/main/docker/Dockerfile) which installs the latet PyPI release of Tern. Once we cut our next release the cyclonedxjson format will be recognized.

**Comment by rnjudge** [comment]
For now, if you want to use cyclonedxjson format in a container, you can use the ci Dockerfile that installs Tern's dependencies and clones + builds + installs the latest version of Tern: https://github.com/tern-tools/tern/blob/main/ci/Dockerfile

**Comment by nexeh** [comment]
This makes a lot of sense @rnjudge! Thanks for the fast reply. Ill look into using the CI image you suggested. How often do you release? No pressure, just curious on your normal release cadence.
