### ISSUE TITLE
How to crosscheck the FOSS packages detected by tern?

### ISSUE THREAD

**Issue by Raghavendrakamatagi-eng** [tern-tools/tern#1168]
Hello Team,

One question,

How to verify the FOSS packages detected by tern are used in our project or not, since we found that some packages are coming under strong copyleft license e.g.GPLv3+. Kindly confirm

Thanks in advance.

**Comment by rnjudge** [comment]
Hi @Raghavendrakamatagi-eng if you have the source code for the packages that you want to cross-check you can confirm there. Otherwise, Tern uses the package manager to collect license information reported by the package publisher/author (with the exception of Debian-based packages which parses copyright text). If you want to see for yourself how these commands are run you can login to the interactive shell of your container and run the commands from [base.yml ](https://github.com/tern-tools/tern/blob/0b87b0c039b799df6e9883be07fe92469f510e0e/tern/analyze/default/command_lib/base.yml)there.

Let me know if you have any more questions.
