### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by Jeeppler** [tern-tools/tern#1244]
**Ask your question here**

Is this project still alive? Last merge was in July.

**Comment by rnjudge** [comment]
Hi @Jeeppler - we're still here! I haven't put out a release because there hasn't been new functionality added. @armintaenzertng opened a PR to update some of the SPDX generation and we were waiting on scancode to update a dependency. That was done recently so this PR is probably ready to merge and then I can put out a new release with all the updated functionality and deps.

**Comment by Jeeppler** [comment]
@rnjudge thank you for the fast reply. Awesome to hear that this project is still alive 👍

**Comment by armintaenzertng** [comment]
Just a heads-up: The PR in scancode was merged indeed, but there has been no new scancode release since then.
When I find the time, I can try to test the tern PR with the current state of the scancode repo.
