### ISSUE TITLE
Enable pip package listing

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#149]
**Describe the Feature**
Tern currently only lists OS level packages. It should also list language level packages like pip

**Use Cases**
For containers with python apps

**Implementation Changes**
Add `pip` binary in `command_lib/base.yml`. Then add under it use `pip-licenses` to list pip licenses. This requires pip-licenses to be installed.

**Comment by sschuberth** [comment]
For language-level packages, how about if Tern would offer a mechanism to run third-party tools like the [ORT analyzer](https://github.com/heremaps/oss-review-toolkit#analyzer), similar to the [suggestion to be able to use an external license scanner](https://github.com/vmware/tern/issues/284)? ORT will soon also take curations from ClearlyDefined into account, so that would solve https://github.com/vmware/tern/issues/160, too.

**Comment by nishakm** [comment]
> For language-level packages, how about if Tern would offer a mechanism to run third-party tools like the [ORT analyzer](https://github.com/heremaps/oss-review-toolkit#analyzer), similar to the [suggestion to be able to use an external license scanner](https://github.com/vmware/tern/issues/284)?

#284 is meant to just allow an external tool to scan files within a container image. So whatever ORT produces is what tern will report. Does this work for you?

**Comment by sschuberth** [comment]
I believe that would work. At first I thought you'd want to distinguish between running a license scanner and running a dependency analyzer, but I can see that you probably don't care about which tool you're running exactly at this stage, or what kind of output it produces.

**Comment by ForgetMe17** [comment]
Can I use this as the proposal for GSoC?

**Comment by nishakm** [comment]
> Can I use this as the proposal for GSoC?

I believe @abhaykatheria is currently trying to figure this out. `pip` isn't the only one we need to enable. Golang is particularly difficult. Enabling it needs to be done by June though, so (hopefully) it would be almost completed by summer.

**Comment by abhaykatheria** [comment]
I wrote the required scripts for **pip** **npm** and **gem**. But go follows whole other approach so yeah its really difficult i am currently working on it.

**Comment by abhaykatheria** [comment]
I will open a pr soon for this issue.

**Comment by sschuberth** [comment]
Out of curiosity @abhaykatheria, what's the reason for reimplementing getting the dependencies for *pip*, *npm* and *gem* instead of just leveraging the [ORT analyzer](https://github.com/oss-review-toolkit/ort#details-on-the-tools) as [suggested above](https://github.com/vmware/tern/issues/149#issuecomment-534964493) which already supports all of these plus *Go* and more?

**Comment by nishakm** [comment]
@sschuberth Is there a python library for the ORT analyzer?

**Comment by sschuberth** [comment]
No @nishakm, but it has a generic CLI that you can simply call.

**Comment by nishakm** [comment]
> No @nishakm, but it has a generic CLI that you can simply call.

In that case, ORT may be a good candidate to implement as an extension. We've already done this for [Scancode](https://github.com/vmware/tern#scancode).
