### ISSUE TITLE
Ignore empty layers rather than exiting

### ISSUE THREAD

**Issue by 00032118** [tern-tools/tern#686]
Scratch is a special basic image. When compiled into an image file, it will generate empty image layer files layers, and will report an error when tern is checked.

**Comment by nishakm** [comment]
Can you help me understand this issue more? Is Tern failing to analyze an image which was built with a Dockerfile that just has `FROM scratch` in it?

**Comment by 00032118** [comment]
Yes, for example, the older version of the image busybox, the dockerfile is as follows, there will be empty layers after decompression in the generated image, and the tern scan will report an error.
FROM scratch
ADD busybox.tar.xz /
CMD ["sh"]


forexample: https://github.com/docker-library/busybox/blob/master/uclibc/Dockerfile

**Comment by nishakm** [comment]
One can either give tern an image (using `-i` option) or a Dockerfile (using `-d`) option. If a Docker image was built successfully with the Dockerfile above, Tern can successfully scan it because there will be 1 non-empty layer. If this Dockerfile was provided to Tern, tern will attempt to run `docker build` on this Dockerfile. If the build fails because `busybox.tar.xz` is not available in the filesystem, it will not be able to analyze the image. It will, however, attempt to analyze the FROM image. However, since the image is `scratch` it will say it cannot analyze `scratch` and exit gracefully. So failing to analyze this kind of Dockerfile in this kind of situation is the expected outcome.

**Comment by 00032118** [comment]
I do n’t understand what your reply means. I have an empty layer in the busybox I introduced in the following way, and the tern scan will fail
FROM docker.artnj.zte.com.cn/cci/cdb/busybox:latest

**Comment by 00032118** [comment]
Thanks, you mean that normal mirrors should have no empty layers, right? My current image is an old version, it is possible that docker build can introduce empty layers.

**Comment by nishakm** [comment]
I have not come across a Docker image with a manifest that contains empty layers. The closest I can get to that scenario is if someone used `RUN mkdir foo` in their Dockerfile which would create a directory with no content in it. This is technically not an empty layer since the directory exists. Can you provide an example I can take a look at? Then we could possibly test a situation where there is an empty layer and instead of exiting, record a notice that it is empty and continue on.

**Comment by 00032118** [comment]
I can't provide you with the complete image file, but I can provide the layers with problematic image files. How to give it to you, it seems that you can't submit documents.

**Comment by nishakm** [comment]
I found some images that do have empty layers. I will work towards a fix
