### ISSUE TITLE
Proposal: Use licensee to parse LICENSE file

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#71]
Tern mostly relies on a package manager's license field but this may not be filled in. For example dpkg does not have a 'license' field. Instead the snippet reads the contents of the LICENSE file and dumps the result.

Look at https://github.com/benbalter/licensee to do all of the work

Options:
1. Just use it: This would mean adding ruby and gem as a dependency for Tern and this goes against my general motivation to minimize the number of dependencies Tern uses.
2. Find a python3 equivalent: I have not been able to find one
3. Create a simply python3 utility that does what licensee does: This would involve duplicating development work on something far more sophisticated

**Comment by nishakm** [comment]
@Abhigupta4981 that looks like it's meant to maintain licenses not interpret LICENSE files. Debian and Ubuntu's package managers do not use any kind of metadata to store licenses and instead retain the software's license file. Here we just dump the contents of the license file and that makes the report unreadable. Did you take a look at https://github.com/benbalter/licensee?

**Comment by gregwebs** [comment]
There is [go code](https://github.com/pmezard/licenses) that does the same thing as licensee (it is specialized to retrieve go licenses, but you could remove that part). That would make for a single binary install rather than ensuring a language interpreter exists.

**Comment by gregwebs** [comment]
I will send a PR to build a docker image for tern, which would make for an easy way to distribute python with a go binary.

**Comment by gregwebs** [comment]
ahh, looks like this shells out to docker instead of using the docker API: that makes it a lot more difficult to run from a docker container.

**Comment by nishakm** [comment]
#160 may be able to solve this

**Comment by sschuberth** [comment]
Also see [A Comparison Study of Open Source License Crawler](https://osr.cs.fau.de/2019/08/07/final-thesis-a-comparison-study-of-open-source-license-crawler/), which includes `licensee`, and doesn't attest it to have a high license recognition rate. [ScanCode](https://github.com/nexB/scancode-toolkit), which we also use in [ORT](https://github.com/heremaps/oss-review-toolkit) by default, seems to be much better. ScanCode has also been mentioned as part of https://github.com/vmware/tern/issues/284, so it probably makes sense to use the same tool here and there (yes, ScanCode can also scan single files). Another bonus: ScanCode is written in Python, though version 2 instead of 3, but maybe you guys can [help out with the transition](https://github.com/nexB/scancode-toolkit/issues/295).

**Comment by nishakm** [comment]
Another bonus: ScanCode is written in Python, though version 2 instead of 3, but maybe you guys can [help out with the transition](https://github.com/nexB/scancode-toolkit/issues/295).

I'm working on this in regards to #284 slated for the November release. I can try ScanCode with Python 3 now and take it from there.

**Comment by nishakm** [comment]
Closing this. We have used [debut](https://github.com/nexB/debut/) to parse Debian style copyright files.
