### ISSUE TITLE
Recognize install snippets that follow environment variable declarations

### ISSUE THREAD

**Issue by rnjudge** [tern-tools/tern#770]
**Describe the Feature**
It is common in Dockerfiles that build go apps to set some environment variables before running the actual snippet that might install go modules. For example:
```
RUN CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo -o swag cmd/swag/main.go
```

For the above line, Tern currently does not recognize "go build" as a snippet to install modules, despite that snippet being listed in snippets.py. This issue proposes changes to the way Tern parses 

**Use Cases**
See golang example above.

**Implementation Changes**
Changes to `filter_install_commands()` or other associated functions, like `split_command()`, to better filter through potential environment variables that might come before a snippet install command.

**Comment by ForgetMe17** [comment]
This is kind of bug for now, because our parser will consider 
`RUN CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo -o swag cmd/swag/main.go`
as a `variable assignment`. Here are the result.
```
{'content': 'CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .',
 'variable': {'name': 'CGO_ENABLED',
              'value': '0 GOOS=linux go build -a -installsuffix cgo -o app .'}}
```

**Comment by ForgetMe17** [comment]
I can take on this issue! @rnjudge 
We can modify `parse_shell_variables_and_command()` in `tern\utils\general.py`. We can loop on a search for the `variable_pattern` until we can not find the macthed case.
For command `CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo -o swag cmd/swag/main.go`:
1. Extract `CGO_ENABLED=0` by `^([A-Za-z_][A-Za-z0-9_]*)=(.*) ` and the remaining part should be `GOOS=linux go build -v -a -installsuffix cgo -o swag cmd/swag/main.go`.
2. Extract `GOOS=linux` by `^([A-Za-z_][A-Za-z0-9_]*)=(.*) ` and the remaining part should be `go build -v -a -installsuffix cgo -o swag cmd/swag/main.go`.
3. The remaining part does not contains a `variable_pattern` so it should be `command`.

Note that this method only works on the condition that the `variable assignment` are followed by `command` which should be a common case. The reason is that we are looking for a `variable assignment` from the start of command.

**Comment by nishakm** [comment]
@ForgetMe17 do you still want to work on this?

**Comment by ForgetMe17** [comment]
@nishakm I will try on it!
