### ISSUE TITLE
Generate SBoM per layer

### ISSUE THREAD

**Issue by nishakm** [tern-tools/tern#840]
**Describe the Feature**
Rather than generate SBoM for the whole container image, generate it for a specific layer.

**Use Cases**
- This feature will be useful in generating SBoMs for each container layer as a client builds.
- This feature can also be used during a container image "debugging" run where Tern analyzes a single container image.

**Implementation Changes**
This is related to #660

**Comment by aalexanderr** [comment]
I'd like to ask whats the status on this feature? We have tools that do static analysis of Dockerfiles and generate SBoM but it doesn't work on base images so a feature where we could just do analysis of first layer would be really useful.

**Comment by nishakm** [comment]
> I'd like to ask whats the status on this feature? We have tools that do static analysis of Dockerfiles and generate SBoM but it doesn't work on base images so a feature where we could just do analysis of first layer would be really useful.

It's slated for Release 3.0.0 due next year in March.

**Comment by aalexanderr** [comment]
Can I help to have this feature quicker?

**Comment by nishakm** [comment]
@rnjudge, would you be able to assign some tasks to @aalexanderr towards this feature?

**Comment by rnjudge** [comment]
Hi @aalexanderr glad to see your interest on this. For this feature we need to do a few things:

1) Add a report command line option to pick the layer you want to generate the SBoM for. I am imagining something like `tern report -l <Layer 1,2,3etc>` or `tern report --layer <1,2,3>. 
2) When the layer is selected, we want to mount the container layers up until the selected layer. There is functionality that does this already that will need some slight logic adjustment if the `--layer` option is envoked.
3) Print the layer info for only the selected layer. We will need to make accommodations to do this in each report format `generator.py` file but for now we can start with the default report in `tern/formats/default/generator.py`

In the mean time, have you tried running Tern on your base images? The general report will break the SBoM down by layers, but you could ignore the other layers and just use the base layer SBoM until this feature is implemented.

**Comment by rnjudge** [comment]
@aalexanderr I added some good first steps towards implementing this feature (#845, #846). Let me know if you are interested in working on either of them :)

**Comment by aalexanderr** [comment]
@rnjudge  As for scanning base images only - that would be lovely but I've seen no way of getting base image name from docker (tried dfimage & dive) It might be possible to take out the first layer, tag it and run a scan on it but I believe its better to contribute directly here rather than hack around when you already have this feature planned for nearest release.

I will work on both of them, before I start pushing I just need to go through some corporate approvals (It will take 3-4 days). Thanks a lot for the task break-down!

**Comment by rnjudge** [comment]
@aalexanderr Sounds good! I will assign them to you now. Please note that we are heading in to the holidays and any PR you open between now and January 4th when I'm back from vacation may take a few extra days to review. Appreciate your interest and help on this!

**Comment by rnjudge** [comment]
Once tasks 845 and 846 are completed the next step will be to actually implement the single layer report formatting for each reporting style in `generator.py`. 

I suggest starting with the default report format. 
- For the default report format, we will need to add a new function, `print_single_layer()` to `tern/formats/default/generator.py`. This function will take in the `image` object and `print_layer` variable and should only print the report information for that given layer in the image object. Hint: use the image's `layers` property to locate the layer in the image object. From there, each `ImageLayer` will have a `layer_index` property that is the index position of the layer in relationship to the other layers in the image (base OS is layer 1).
- We will also need to change the logic in the `generate()` function to call the `print_single_layer` function if the `print_layer` variable exists, otherwise, continue to call `print_full_report()`. `print_single_layer()` can make use of the existing functions in `tern/formats/default/generator.py` that print layer-specific information.

**Comment by aalexanderr** [comment]
Hi, I've made the PR: #847 

I've also made the changes for analysis of an image until specified layer and the default txt reporter (locally for now).

Before submitting I wanted to ask how you want it to work with multi-image Dockerfiles?

In reporting there is looping over images (I'm assuming it's due to aforementioned multi-image Dockerfiles). Should the --layer param work only images only or should it analyze last image until given layer?

**Comment by rnjudge** [comment]
> Before submitting I wanted to ask how you want it to work with multi-image Dockerfiles?
> 
> In reporting there is looping over images (I'm assuming it's due to aforementioned multi-image Dockerfiles). Should the --layer param work only images only or should it analyze last image until given layer?

This is an interesting question. For multistage Dockerfiles, Tern analyzes each stage as a separate Dockerfile. If we want to handle multistage Dockerfiles for single layer reporting we will need a way to specify the stage of the Dockerfile to report on in conjunction with a particular layer of that stage. Adding another command line option to specify the stage seems bulky, though. Alternatively, we could consider each line of the dockerfile it's own "layer". This would make it easy for the user to specify which "layer" they want the output report for. For example, if the user wanted to get the analysis report for line 4, they would specify layer 4 on the command line and we could adjust the layer number in accordance with the stage on the backend? Doing it this way would just need to be documented.

```
(line 1) FROM scratch (layer1)
(line 2) COPY app.go . (layer 2)
(line 3) RUN make . (layer 3)

(line 4) FROM alpine:latest  (layer 4)
(line 5) RUN apk --no-cache add ca-certificates (layer 5)
(line 6) WORKDIR /root/ (layer 6)
(line 7) CMD ["./app"]  (layer 7)
```

We also have a couple other options... 1) Assume the layer input is for the first stage only. 2) Defer the implementation for multistage Dockerfiles right now and only consider single stage Dockerfiles or images. What makes the most sense to you as a user?

Your question also reminds me that will need some sort of boundary error checking to make sure the user doesn't specify a layer number that doesn't exist (maybe your PR already has this).

**Comment by rnjudge** [comment]
@aalexanderr I've been thinking about this and think we should just focus on enabling this feature for images right now. We can skip it for now with Dockerfile inputs.

**Comment by aalexanderr** [comment]
@rnjudge I misunderstood the requirements and went with both analysis & report until given layer (thus my comment about until_layer seeming to be better name). How about having both options, as in:
   1. --layer -l Print report only for given layer, or 
   1.  --until-layer -ul Print report for all layers until given layer (including given layer).
I think the until-layer feature could be useful - e.g. CI resources are often restricted, some pay per used resources in CI. Project could reserve some amount of layers for external dependencies (which might change license if not version-locked) and keep checking only those for license compliance.

As for guards against out of bounds - yeah, didn't add it yet but thought about it too.

As for Dockerfiles - I will ignored them (as in using -l option with -d will result in error).

As for user opinion:
I think either last image should be analyzed (as that is the image that might get pushed to registry and some registries have issues with specific licenses- which is why I'm here) - but this can be also achieved with building multi-stage/image dockerfile and analyzing final image. I think that additional flag to provide which image's layer is to be checked (counting from 1 again, defaulting to 1) might be most straightforward to use.

**Comment by rnjudge** [comment]
> @rnjudge I misunderstood the requirements and went with both analysis & report until given layer (thus my comment about until_layer seeming to be better name). How about having both options, as in:
> 
>     1. --layer -l Print report only for given layer, or
> 
>     2. --until-layer -ul Print report for all layers until given layer (including given layer).
>        I think the until-layer feature could be useful - e.g. CI resources are often restricted, some pay per used resources in CI. Project could reserve some amount of layers for external dependencies (which might change license if not version-locked) and keep checking only those for license compliance.
> 

Instead of adding another option that takes a number as input, could we keep the `--layer` CLI option and then add some sort of `--inclusive` T/F flag that could be used in conjunction with the --layer option if the user wants to include up until that layer? If that seems more confusing let me know but since it's basically the same option with just a yes or no to including the previous layers a T/F flag seems more appropriate to me and we also wouldn't need to then worry about guarding against the user trying to use --layer and --layer-until at the same time. Let me know if you disagree or have other thoughts. Really appreciate your help moving this forward!


> As for user opinion:
> I think either last image should be analyzed (as that is the image that might get pushed to registry and some registries have issues with specific licenses- which is why I'm here) - but this can be also achieved with building multi-stage/image dockerfile and analyzing final image. I think that additional flag to provide which image's layer is to be checked (counting from 1 again, defaulting to 1) might be most straightforward to use.

Since we are no longer considering the multistage-dockerfile-as-an-input use case, our only choice is to analyze the last image. If the image given to Tern is the result of a multistage dockerfile, Docker will throw away any previous build stages anyway and the result is the last image that the user would then give to Tern to analyze. So the number that gets inputted on the command line can be interpreted as a straightforward layer number and we would just need to out of bounds guards like you mentioned.

**Comment by aalexanderr** [comment]
> Instead of adding another option that takes a number as input, could we keep the `--layer` CLI option and then add some sort of `--inclusive` T/F flag that could be used in conjunction with the --layer option if the user wants to include up until that layer? If that seems more confusing let me know but since it's basically the same option with just a yes or no to including the previous layers a T/F flag seems more appropriate to me and we also wouldn't need to then worry about guarding against the user trying to use --layer and --layer-until at the same time. Let me know if you disagree or have other thoughts. Really appreciate your help moving this forward!

Thats better! 

--inclusive should default to true or false? shorthand -in? 

>Since we are no longer considering the multistage-dockerfile-as-an-input use case, our only choice is to analyze the last image. If the image given to Tern is the result of a multistage dockerfile, Docker will throw away any previous build stages anyway and the result is the last image that the user would then give to Tern to analyze. So the number that gets inputted on the command line can be interpreted as a straightforward layer number and we would just need to out of bounds guards like you mentioned.

It seems to me that multi-stage dockerfiles are already partially implemented, I turned off the --layer feature for Dockerfile analysis alltogether, I'd rather leave it to the tern team if thats ok.
I'll gladly cover: image analysis until given layer (in the analysis part), reporting for single layer and until layer  (with --inclusive cli arg) and default+html formaters. I need to clean it up a bit, test it a bit more and I'll publish it.
I'll have additional PR for utilizing all cores for scancode as discussed with @nishakm and will have take off to work for my main tasks.

**Comment by rnjudge** [comment]
> > Instead of adding another option that takes a number as input, could we keep the `--layer` CLI option and then add some sort of `--inclusive` T/F flag that could be used in conjunction with the --layer option if the user wants to include up until that layer? If that seems more confusing let me know but since it's basically the same option with just a yes or no to including the previous layers a T/F flag seems more appropriate to me and we also wouldn't need to then worry about guarding against the user trying to use --layer and --layer-until at the same time. Let me know if you disagree or have other thoughts. Really appreciate your help moving this forward!
> 
> Thats better!
> 
> --inclusive should default to true or false? shorthand -in?

@aalexanderr  I think default to False (so printing the information for one single layer is the default) and then we can just add a pointer in the "help" for the `--layer` option about the additional `--inclusive` flag. Shorthand -in sounds good to me as well.

> > Since we are no longer considering the multistage-dockerfile-as-an-input use case, our only choice is to analyze the last image. If the image given to Tern is the result of a multistage dockerfile, Docker will throw away any previous build stages anyway and the result is the last image that the user would then give to Tern to analyze. So the number that gets inputted on the command line can be interpreted as a straightforward layer number and we would just need to out of bounds guards like you mentioned.
> 
> It seems to me that multi-stage dockerfiles are already partially implemented, I turned off the --layer feature for Dockerfile analysis alltogether, I'd rather leave it to the tern team if thats ok.

Yes, sorry if I wasn't clear in my explanation above. We will leave the --layer feature turned off for all Dockerfile analysis unless we see a lot of user demand for it :) 

> I'll gladly cover: image analysis until given layer (in the analysis part), reporting for single layer and until layer (with --inclusive cli arg) and default+html formaters. I need to clean it up a bit, test it a bit more and I'll publish it.

Fantastic! Your work is much appreciated. Let me know if you'd like any help testing. Feel free to open a work-in-progress PR.

> I'll have additional PR for utilizing all cores for scancode as discussed with @nishakm and will have take off to work for my main tasks.

Sounds great!

**Comment by rnjudge** [comment]
This issue was resolved. Closing.
